### ISSUE TITLE
Have you a found a way to...

### ISSUE THREAD

**Issue by lopugit** [nickp10/shuffler#5]
Just wondering if you've found a way to add songs to multiple playlists at once, I have multiple playlists for specific genres and feelings, but sometimes I want to add a song to more than 1 playlist, currently I have to spend easily 20 seconds clicking - clicking - clicking to add the same song to different playlists, super annoying and takes you out of the flow of the music but I don't want to miss the awesome song I found on this radio station!!!

**Comment by nickp10** [comment]
This is not an issue related to this project. You'll need to contact YouTube to add that ability to multiselect playlists when adding a song to a playlist.
